#!/bin/bash
: <<COMMENT
  Copyright (C) 2012 Tri Le <trile7 at gmail dot com>

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation version 3.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
COMMENT

$fm_import
if [[ -z $fm_pwd ]]; then
  echo "This script is intended to be run with spacefm only."
  exit 1
fi
if [[ ${#fm_files[@]} -ge 2 ]]; then
  newfile=${fm_value:=combined.pdf}
  filename=`basename "$newfile"`
  foldername=`dirname "$newfile"`
  while [[ -e $newfile ]]; do
    (( j++ ))
    newfile=$foldername/$filename'_'$j
    if [[ $j -gt 99 ]]; then
      echo "Output file exists"
      exit 1
    fi
  done
  mkdir -p "$foldername"
  gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile="$newfile" "${fm_files[@]}" && rm "${fm_files[@]}"
else
  echo "At least 2 PDF files are needed to merge."
  exit 1
fi
