#!/bin/bash
: <<COMMENT
  Copyright (C) 2012 Tri Le <trile7 at gmail dot com>

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation version 3.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
COMMENT

$fm_import
if [[ -z $fm_pwd ]]; then
  echo "This script is intended to be run with spacefm only."
  exit 1
fi
if [[ $fm_file ]]; then
  if [[ `echo $fm_value | wc -w` -eq 6 ]]; then
    opt=$fm_value
  else
    opt="-delay 2 -loop 0 -resize 800x600>"
    echo "Expecting 6 variables.  Default options $opt is used."
  fi
  display -coalesce -auto-orient -immutable $opt "${fm_files[@]}"
else
  echo "Select images to view as slideshow"
fi
